exports.HTTP_OK = 200;
exports.HTTP_CREATED = 201;
exports.HTTP_NOT_MODIFIED = 304;
exports.HTTP_BAD_REQUEST = 400;
exports.HTTP_UNAUTHORIZED = 401;
exports.HTTP_FORBIDDEN = 403;
exports.HTTP_NOT_FOUND = 404;
exports.HTTP_CONFLICT = 409;
exports.HTTP_INTERNAL_SERVER_ERROR = 500;
exports.HTTP_UNPROCESSABLE_ENTITY = 422;
exports.HTTP_UNSUPPORTED_MEDIA_TYPE = 415;


exports.HTTP_SERVICE_UNAVAILABLE = 503;
exports.HTTP_GATEWAY_TIMEOUT = 504;
exports.HTTP_METHOD_NOT_ALLOWED = 405;
exports.HTTP_LENGTH_REQUIRED = 411;
exports.HTTP_REQUEST_ENTITY_TOO_LARGE = 413;
exports.HTTP_REQUEST_URI_TOO_LONG = 414;
